name: pashudrishti
description: "Pashu Drishti - Livestock Management System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  provider: ^6.0.0
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  image_picker: ^1.0.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
